# Generated by Django 5.1.2 on 2024-11-02 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_incident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=20, unique=True)),
                ('reporters_id', models.CharField(max_length=20, null=True)),
                ('reporter', models.CharField(max_length=40)),
                ('details', models.TextField()),
                ('reported_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=15)),
                ('enterprise', models.BooleanField(default=False)),
                ('government', models.BooleanField(default=False)),
            ],
        ),
    ]
