# Generated by Django 5.1.2 on 2024-11-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_incident', '0002_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='reporter',
            new_name='reporter_name',
        ),
    ]
